server:
  port: 30900
  servlet:
    context-path: /api/v2/open-api
spring:
  application:
    name: service-api-open-api
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: desc=开放API接口
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
