server:
  port: 30400
  servlet:
    context-path: /api/v1/basic
spring:
  application:
    name: service-api-basic
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: desc=海露基础服务
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  mvc:
    static-path-pattern: /**
  resources:
    # 外部文件存储目录
    static-locations: file:${file.store.path}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: select 1
      min-idle: 5
      max-active: 20
      max-wait: 60000
      use-global-data-source-stat: true
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,log4j
      initial-size: 10
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: ehcache
  jackson:
    default-property-inclusion: non_null

redis:
  hostname: 192.168.10.243
  port: 6379

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 6000

mail:
  sender: 默认邮件发送人

static:
  # 编辑器图片、文件、视频访问前缀
  server:
    prefix: http://localhost:8082/api/v1/basic

file:
  store:
    path: /opt/filestore

uid:
  epochStr: 2019-11-11

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hailu.cloud.api.*.module.*.entity
  mapper-locations: classpath*:/com/hailu/cloud/api/**/*Mapper.xml
