server:
  port: 30400
  servlet:
    context-path: /api/v2/basic
  max-http-header-size: 20KB
spring:
  application:
    name: service-api-basic
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: management.context-path=${server.servlet.context-path}/actuator,desc=海露基础服务
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  mvc:
    static-path-pattern: /**
  resources:
    # 外部文件存储目录
    static-locations: file:${file.store.path}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: select 1
      min-idle: 1
      max-active: 4
      initial-size: 1
      max-wait: 60000
      use-global-data-source-stat: true
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,log4j
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: ehcache
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

redis:
  hostname: 192.168.10.243
  password: hl@1688.+soft.redis
  port: 6379

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

mail:
  sender: 默认邮件发送人

static:
  # 编辑器图片、文件、视频访问前缀
  server:
    prefix: http://127.0.0.1:30000/api/v2/basic

file:
  store:
    path: /opt/filestore

uid:
  epochStr: 2019-11-11

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hailu.cloud.api.*.module.*.entity
  mapper-locations: classpath*:/com/hailu/cloud/api/**/*Mapper.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
