sms:
  free:
    server:
      sname: dlhqin00
      spwd: Ha999999
      scorpid:
      sprdid: 1012888
      sms-prefix: 【海露物联】
      # 免费短信接口地址
      address: http://api.51welink.com
  template:
    vericode:
      # 验证码方案
      text: 您正在登录验证，验证码{0}，30分钟内有效，切勿将验证码泄露于他人。
      # 过期时间，单位秒, 默认30分钟
      expire: 1800