server:
  port: 33000
  servlet:
    context-path: /api/v1/auth
spring:
  application:
    name: service-api-auth
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: desc=登录授权认证接口