server:
  port: 30700
  servlet:
    context-path: /api/v1/payment
spring:
  application:
    name: service-api-payment
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: desc=支付接口
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: select 1
      min-idle: 5
      max-active: 20
      max-wait: 60000
      use-global-data-source-stat: true
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,log4j
      initial-size: 10

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hailu.cloud.api.*.module.*.entity
  mapper-locations: classpath*:/com/hailu/cloud/api/**/*Mapper.xml
