server:
  port: 30000
spring:
  application:
    name: service-gateway
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: desc=网关

mapping:
  swaggerDocs:
    service-api-auth: 海露认证服务-接口文档
    service-api-admin: 海露后台管理系统-接口文档
    service-api-mall: 海露商城-接口文档
    service-api-notify: 海露通知服务-接口文档

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 6000