spring:
  cloud:
    gateway:
      routes:
        - id: service-api-auth
          uri: lb://service-api-auth
          predicates:
            - Path=/api/v1/auth/**
        - id: service-api-admin
          uri: lb://service-api-admin
          predicates:
            - Path=/api/v1/admin/**
        - id: service-api-mall
          uri: lb://service-api-mall
          predicates:
            - Path=/api/v1/mall/**
        - id: service-api-basic
          uri: lb://service-api-basic
          predicates:
            - Path=/api/v1/basic/**
        - id: service-api-xinan
          uri: lb://service-api-xinan
          predicates:
            - Path=/api/v1/xinan/**
        - id: service-api-payment
          uri: lb://service-api-payment
          predicates:
            - Path=/api/v1/payment/**
        - id: service-api-merchant
          uri: lb://service-api-merchant
          predicates:
            - Path=/api/v1/merchant/**
      default-filters:
        - SwaggerHeaderFilter
