#version: /api/v2
mapping:
  auth:
    # 以下请求地址不需要登录也能访问
    exclude:
      endsWith:
        - swagger-ui.html
        - api-docs
        - .jpg
        - .jpeg
        - .png
        - .zip
        - .tar
        - .mp4
        - .pdf
      startsWith:
        # 登录授权接口
        - ${api-version}/auth
        # 支付接口
        - ${api-version}/payment
        # 基础服务接口
        - ${api-version}/basic
        - ${api-version}/basic/ueditor
        - ${api-version}/basic/upload
        - ${api-version}/basic/sms
        - ${api-version}/basic/debug
        - ${api-version}/basic/nation
        - ${api-version}/basic/version/findDetail
        - ${api-version}/basic/version
        - ${api-version}/basic/uuid/create
        # 心安接口
        - ${api-version}/xinan/app/xinan/register
        - ${api-version}/xinan/app/xinan/updatePassword
        - ${api-version}/xinan/app/xinan/wetChatSubmitPhone
        - ${api-version}/xinan/payment/callbackWechat
        - ${api-version}/xinan/payment/callbackWechatHl
        - ${api-version}/xinan/nation
        - ${api-version}/xinan/app/xinanhelp/findMutualAidList
        - ${api-version}/xinan/app/xinanhelp/MutualAidDetails
        - ${api-version}/xinan/app/xinanhelp/MutualAidPictur
        - ${api-version}/xinan/app/home
        - ${api-version}/xinan/app/xinan/CommonwealArticle
        - ${api-version}/xinan/app/xinan/publicInterestList
        - ${api-version}/xinan/app/xinan/detailed
        - ${api-version}/xinan/app/join/findInsurdPrice
        # 商户接口
        - ${api-version}/merchant/app/merchantLogin
        - ${api-version}/merchant/merchant/pc/register
        - ${api-version}/merchant/mcManagementType/businessType
        - ${api-version}/merchant/merchant/register
        # 商城接口
        - ${api-version}/mall/payment/callback/weixin
        - ${api-version}/mall/api/capacity
        - ${api-version}/mall/api/mall/findByGcIdQueryGoods
        - ${api-version}/mall/api/mall/getHomeList
        - ${api-version}/mall/api/mall/findClassifyRecommend
        - ${api-version}/mall/api/mall/getListGoodsClass
        - ${api-version}/mall/api/mall/getGoodsClass
        - ${api-version}/mall/api/mall/getParentClassList
        - ${api-version}/mall/api/mall/getReserveAndNew
        - ${api-version}/mall/api/mall/getGoodsKeyWords
        - ${api-version}/mall/api/mall/getGoodsInfo
        - ${api-version}/mall/api/mall/getNewGoods
        - ${api-version}/mall/api/mall/findSshtList
        - ${api-version}/mall/api/mall/getCartRecommend
        - ${api-version}/mall/api/mall/getGoodsRecommend
        - ${api-version}/mall/api/mall/iconList
        - ${api-version}/mall/api/mall/helpCentre
        - ${api-version}/mall/api/mall/allQuestionsByGoodsId
        - ${api-version}/mall/api/mall/goodsAllEevaluate
        - ${api-version}/mall/ManagementType/find/queryBusinessType
        - ${api-version}/mall/shoppingAddressList
        - ${api-version}/mall/app/multiIndustry/shopEnquiry
        - ${api-version}/mall/app/multiIndustry
        - ${api-version}/mall/ManagementType
        - ${api-version}/mall/api/user/getInfoByCode
        - ${api-version}/mall/api/user/getJsApiSignature

  login-type:
    # 开启debug后, notAllow将不对登录类型做请求限制
    debug: true
    # 不允许访问的路径 【0，1】具体看 LoginTypeEnum
    notAllow:
      0:
        - ${api-version}/admin
        - ${api-version}/merchant
      1:
        - ${api-version}/admin
        - ${api-version}/xinan
        - ${api-version}/mall
