server:
  port: 30000
spring:
  application:
    name: service-gateway
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: desc=网关

mapping:
  swaggerDocs:
    service-api-auth: 海露认证服务-接口文档
    service-api-admin: 海露后台管理系统-接口文档
    service-api-mall: 海露商城-接口文档
    service-api-basic: 海露基础服务-接口文档
    service-api-xinan: 心安接口-接口文档
    service-api-payment: 海露支付服务-接口文档
    service-api-merchant: 海露商户服务-接口文档
  auth:
    exclude:
      endsWith:
        - swagger-ui.html
        - api-docs
        - .jpg
        - .jpeg
        - .png
        - .zip
        - .tar
        - .mp4
        - .pdf
      startsWith:
        - /api/v1/auth
        - /api/v1/xinan
        - /api/v1/basic
        - /api/v1/basic/upload
        - /api/v1/basic/sms
        - /api/v1/basic/uuid
        - /api/v1/merchant/life-circle
  login-type:
    # 开启debug后, notAllow将不对登录类型做请求限制
    debug: true
    # 不允许访问的路径 【0，1】具体看 LoginTypeEnum
    notAllow:
      0:
        - /api/v1/admin
      1:
        - /api/v1/admin

# 用于签名的公私密钥
signature:
  public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCv+8iT40G1Mhw3kE9A7F8SDhKQE+sQ4tXpwk5oU6689oQCXvr4VD4heoOQe7+oYwGkhWuIY+/xXF8aOftkj2bl91fHrkhaHOLd+zBzxE7xvwJGq1+yf63+NX6zzi5O+wPvzkIrXrhDQjLuJCkC8RV8fSowAdh/ieMvLTAD5raX1wIDAQAB
  private-key: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAK/7yJPjQbUyHDeQT0DsXxIOEpAT6xDi1enCTmhTrrz2hAJe+vhUPiF6g5B7v6hjAaSFa4hj7/FcXxo5+2SPZuX3V8euSFoc4t37MHPETvG/AkarX7J/rf41frPOLk77A+/OQiteuENCMu4kKQLxFXx9KjAB2H+J4y8tMAPmtpfXAgMBAAECgYAR960oZZJUBibkXhBWwBYKzrNYJiMgs7rZutQXib0Jn5+lwFMeXzeCt91OjJvqUhrHqd7rQMzYLIasiPv2Qz/i5520Gd1fu4D6LKIKv0vvyGow03VKteEI3S2GhGeo+yjv9WP46NmpK0mpLZGUuyFE+AYefXo5bB1VOkNd/8O1eQJBAOmpHOCKsS2w8yno5OG9G9+yVUywdPAR6kr7hkrkMvTnCj/G4WIUg5MQ7NPoqYF2AKhTM1BYTCiduV7amfJJjV8CQQDAzwN63zjw5vq6rDXf1V3aFaH4M8Vcz5qZouMqLTPVoOtB5tTBDee0lb250XmUH1fEX0Q6dhJ6BzSW1BFl/BCJAkB4oRABdFioSBQhbNTNHb5ILF8RKoAUeItGjrfz7f/Io4aNCnXNFt4ejLxXYmQwK+WHAP0a25rl1RegOqcDiKltAkBNwzBkHiOZBY+aOlqALE3t50usDzVKeXChBlEYcaK2RnCb471rH3CUJNCgYRvn4bxENygNbBGHpeBP9LgPqdoBAkAnhVM6NwG53tsaMx8rvpf98ZixgqslRX+nNN6kNGGqM64bTTP4yYWnvFSVqZjMD/8LSAkvODsaZPDtPiroJi/X

feign:
  hystrix:
    enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
