spring:
  cloud:
    gateway:
      routes:
        - id: service-api-auth
          uri: lb://service-api-auth
          predicates:
            - Path=/api/v1/auth/**
        - id: service-api-admin
          uri: lb://service-api-admin
          predicates:
            - Path=/api/v1/admin/**
        - id: service-api-mall
          uri: lb://service-api-mall
          predicates:
            - Path=/api/v1/mall/**
        - id: service-api-basic
          uri: lb://service-api-basic
          predicates:
            - Path=/api/v1/basic/**
      default-filters:
        - SwaggerHeaderFilter
