spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
  mail:
    host: smtp.qq.com
    username: 976778267@qq.com
    password: fnkesrxnzkhbbdjg

#mybatis 在控制台打印sql
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

redis:
  hostname: 192.168.10.243
  password: hl@1688.+soft.redis
  port: 6379