server:
  port: 30500
  servlet:
    context-path: /api/v2/scheduling
  max-http-header-size: 20KB
spring:
  application:
    name: service-api-scheduling
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: management.context-path=${server.servlet.context-path}/actuator,desc=海露任务调度

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

management:
  endpoints:
    web:
      exposure:
        include: "*"
