server:
  port: 30100
  servlet:
    context-path: /api/v1/admin
spring:
  application:
    name: service-api-admin
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: desc=后台管理接口
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: select 1
      min-idle: 5
      max-active: 20
      max-wait: 60000
      use-global-data-source-stat: true
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,log4j
      initial-size: 10
  jackson:
    default-property-inclusion: non_null

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hailu.cloud.api.*.module.*.entity
  mapper-locations: classpath*:/com/hailu/cloud/api/**/*Mapper.xml

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

pagehelper:
  row-bounds-with-count: true
  offset-as-page-num: true
  reasonable: true

user:
  passwd:
    sign:
      # 密码加密的key
      key: hailu.com