server:
  port: 31000
  servlet:
    context-path: /api/v1/admin
spring:
  application:
    name: service-api-admin
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: desc=后台管理接口