server:
  port: 31000
  max-http-header-size: 20KB
spring:
  application:
    name: monitor
  cloud:
    consul:
      discovery:
        register: false
        heartbeat:
          enabled: true
        tags: desc=海露服务监控
  boot:
    admin:
      notify:
        mail:
          to: zhijie_94@163.com
          from: 976778267@qq.com
      discovery:
        ignored-services: consul,monitor
      ui:
        title: 海露服务监控
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>${spring.boot.admin.ui.title}</span>
  security:
    user:
      name: hailu
      password: hl@123