server:
  port: 30600
  servlet:
    context-path: /api/v2/xinan
  max-http-header-size: 20KB
spring:
  application:
    name: service-api-xinan
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: management.context-path=${server.servlet.context-path}/actuator,desc=心安接口
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: select 1
      min-idle: 1
      max-active: 4
      initial-size: 1
      max-wait: 60000
      use-global-data-source-stat: true
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,log4j
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: ehcache
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

#身份证调用信息
id-card:
  url: http://route.showapi.com/1072-1
  showapi-sign: d6e4d493cce6431fb5dfa51b6266d0bd
  showapi-appid: 96312

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hailu.cloud.api.*.module.*.entity
  mapper-locations: classpath*:/com/hailu/cloud/api/**/*Mapper.xml

user:
  passwd:
    sign:
      # 密码加密的key
      key: hailu.com

management:
  endpoints:
    web:
      exposure:
        include: "*"