# 商品后台管理开放出来的共享接口
remote:
  server:
    address: http://192.168.10.243:8080/admin/api

# 提现阀值(元)
income:
  transferout:
    threshold: 100

static:
  # 编辑器图片、文件、视频访问前缀
  server:
    prefix: http://127.0.0.1:30000/api/v2/basic

notify:
  # 支付通知回调地址
  server:
    url: https://dengjunpei.utools.club/api/v2/

merchant:
  commission:
    rate:
      # 区域代理提成
      regional-agent: 0.15
      # 服务商提成

# 宅急送
homedelivery:
  # 密钥
  key: aafc04a1bacb487fa8d03f2a7bfdb555


chinaums:
  key: fcAmtnx7MwismjWNhNKdHC44mNXtnEQeJkRrhKJwyrW2ysRR