spring:
  cloud:
    consul:
      host: 192.168.10.243
      port: 8500

#mybatis 在控制台打印sql
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

redis:
  hostname: 192.168.10.243
  port: 6379