# 商品后台管理开放出来的共享接口
remote:
  server:
    address: http://192.168.10.243:8080/admin/api

# 提现阀值(元)
income:
  transferout:
    threshold: 100

static:
  # 编辑器图片、文件、视频访问前缀
  server:
    prefix: http://127.0.0.1:30000/api/v2/basic

notify:
  server:
    url: http://127.0.0.1:30000/api/v1/

merchant:
  commission:
    rate:
      # 区域代理提成
      regional-agent: 0.15
      # 服务商提成
      service-agent: 0.85

