server:
  port: 30200
  servlet:
    context-path: /api/v1/mall
spring:
  application:
    name: service-api-mall
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: desc=海露商城接口
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: ehcache
  jackson:
    default-property-inclusion: non_null

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 6000
