server:
  port: 30200
  servlet:
    context-path: /api/v1/mall
spring:
  application:
    name: service-api-mall
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: desc=海露商城接口
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: ehcache
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: select 1
      min-idle: 1
      max-active: 4
      initial-size: 1
      max-wait: 60000
      use-global-data-source-stat: true
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,log4j
  jackson:
    default-property-inclusion: non_null

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hailu.cloud.api.*.module.*.entity
  mapper-locations: classpath*:/com/hailu/cloud/api/**/*Mapper.xml

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
