# 系统自定义配置

sys:
  task:
    thread:
      pool:
        # 任务调度最大线程池
        maxsize: 30
  url: ${static.server.prefix}
user:
  passwd:
    sign:
      # 密码加密的key
      key: 79AA9270FD5D4B28A02E616C61B7D7AB
  base:
  maxIntegral:
    # 最大连续签到天数
    day: 7
weixin:
  # 微信开放平台审核通过的应用APPID
  appid:
  # 微信分配的支付密钥
  key:
  # 微信商户号
  mchid:
  # 终端设备号 默认请传[web]
  deviceinfo: WEB
alipay:
  # 支付宝平台审核通过的APPID
  appid:
  # 支付宝分配pid
  pid:
  seller:
    # 支付宝seller_id
    id:
  public:
    # 支付宝公钥
    key:
  rsa:
    private:
      # RSA(SHA1)密钥
      key:
  aes:
    private:
      # AES密钥
      key:
kdniao:
  # 快递鸟用户id
  userId: 1302929
  # 快递鸟apikey
  apiKey: 2dfb7aec-5211-47d5-ab00-d3c8973d421f
app:
  banner:
    ap:
      # app广告分类Id值(轮播图)
      value: 16
  headernews:
    # app文章分类id值(商城头条)
    value: 20
order:
  cancel:
    # 订单取消时间 (小时)
    time: 24
# 短信
lanz:
  sms:
    userid: 864108
    account: wang
    password: 7C4A8D
    # 短信签名
    sign: 【】
    smstype:
      # 用户注册短信验证
      verify: 1
netease:
  sms:
    # 网易短信发送平台配置
    service-url: https://api.netease.im/sms/sendtemplate.action
    verifycode-url: https://api.netease.im/sms/verifycode.action
    templateid: 3097014
    app-key: 853d19b4dcadf6f4cfa46650d3e24711
    app-secret: 8b9b1dd13348
qiniu:
  access-key: test
  secret-key: test
  bucketname: test
redis:
  key:
    user:
      login:
        # 用户token
        token: zyj_server_user_login_token_
        # 用户token过期时间（小时）
        token-times: 720
      registerSmsCode:
        token:
          # 用户短信验证码过期时间（分钟）
          times: 5

#身份证调用信息
id-card:
  url: http://route.showapi.com/1072-1
  showapi-sign: d6e4d493cce6431fb5dfa51b6266d0bd
  showapi-appid: 96312

# 商品后台管理开放出来的共享接口
remote:
  server:
    address: http://192.168.10.243:8080/admin/api

# 提现阀值(元)
income:
  transferout:
    threshold: 100

static:
  # 编辑器图片、文件、视频访问前缀
  server:
    prefix: https://jphailus.utools.club/api/v1/

notify:
  # 编辑器图片、文件、视频访问前缀
  server:
    url: https://jphailus.utools.club/api/v1/

merchant:
  commission:
    rate:
      # 区域代理提成
      regional-agent: 0.15
      # 服务商提成
      service-agent: 0.85