server:
  port: 34000
  servlet:
    context-path: /api/v1/notify
spring:
  application:
    name: service-api-notify
  cloud:
    consul:
      discovery:
        register: true
        heartbeat:
          enabled: true
        tags: desc=海露通知接口
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
redis:
  hostname: 192.168.10.243
  port: 6379

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 6000

mail:
  sender: 默认邮件发送人
